In [8]:
import numpy as np

A = np.array([[0,0,-2],[1,2,1],[1,0,3]])

# 대각행렬을 타이핑하기 어려우므로 B라고 하겠다
# A = PBP^-1
# P^-1AP = B

P = np.array([[-1,0,-2],[0,1,1],[1,0,1]])
invP = np.linalg.inv(P)

B = invP.dot(A.dot(P))
print(B)

# 대각행렬은 고윳값을 대각선에 배치한 행렬이다

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
